# Generated by Django 4.2.16 on 2024-11-19 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.enrollment'),
        ),
    ]
