# Generated by Django 4.2.16 on 2024-11-19 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ManyToManyField(to='courses.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ManyToManyField(limit_choices_to={'role': 'student'}, to=settings.AUTH_USER_MODEL),
        ),
    ]
