# Generated by Django 4.2.16 on 2024-11-19 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_remove_enrollment_course_remove_enrollment_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ManyToManyField(limit_choices_to={'role': 'student'}, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
    ]
