# Generated by Django 4.2.16 on 2024-11-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_first_name_remove_student_last_name'),
        ('courses', '0005_alter_enrollment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ManyToManyField(related_name='enrollments', to='students.student'),
        ),
    ]
