# Generated by Django 4.2.16 on 2024-11-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('attend', 'Attend'), ('absent', 'Absent')], max_length=20),
        ),
    ]
